# Generated by Django 4.2.3 on 2023-07-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_office_recommendations_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='office_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='medical.office'),
        ),
    ]
