# Generated by Django 4.2.3 on 2023-07-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_alter_rating_office_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='recommendations',
        ),
    ]
