# Generated by Django 4.2.3 on 2023-08-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_remove_office_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeform',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='office',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
