# Generated by Django 4.2.3 on 2023-07-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calend', '0007_appointment_day_appointment_month_appointment_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
