# Generated by Django 4.2.3 on 2023-07-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calend', '0008_alter_appointment_day_alter_appointment_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='office_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
